server:
  port: 8010
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @profileActive@
  mail:
    host: smtp.163.com
    username: 13726040244@163.com
    password: nvhdgf537449
    port: 465
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 30000
          timeout: 60000
          writetimeout: 60000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
  boot:
    admin:
      client:
        metadata:
          name: ${security.user.name}
          password: ${security.user.password}
      monitor:
        period: 60000
      discovery:
        enabled: true
      notify:
        mail:
          to: 751523139@qq.com
          from: 13726040244@163.com
      turbine:
        clusters: default
        location: http://localhost:8010
        enabled: true
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream,turbine.stream,activiti
info:
  owner: interface.tolay@gmail.com
  version: @project.version@
management:
  security:
    enabled: false
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@www.gapah.com:8763/eureka/,http://admin:admin@www.gapah.cn:8762/eureka/,http://admin:admin@www.gapah.net:8764/eureka/
  instance:
    instance-id: ${spring.application.name}
    hostname: localhost
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
endpoints:
  metrics:
    enabled: true
turbine:
  app-config: user-service,kreken-provider-uc
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true
