server:
  port: 81
  error:
    include-stacktrace: always
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 1000
  session:
    store-type: redis
  http:
    encoding:
      charset: UTF-8
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  metrics:
    enabled: true
info:
  owner: interface.tolay@gmail.com
  version: @project.version@
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@www.gapah.com:8763/eureka/,http://${security.user.name}:${security.user.password}@www.gapah.cn:8762/eureka/,http://${security.user.name}:${security.user.password}@www.gapah.net:8764/eureka/
  instance:
    instance-id: ${spring.application.name}
    hostname: localhost
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
endpoints:
  metrics:
    filter:
      enabled: true
    enabled: true
service:
    kreken-provider-uc: kreken-provider-uc

